version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
      - ./alerts:/app/alerts  # Map the alerts directory
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=crypto_data
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  db_data:
